#!/bin/sh

APP_NAME=ams
APP_PATH=/home/sniper/manager
APP_PID=/var/run/${APP_NAME}.pid

case "$1" in
start)
    ${APP_PATH}/ams &
    echo $!>${APP_PID}
    ;;
stop)
    if [ -e ${APP_PID} ]; then
        kill `cat ${APP_PID}`
        rm ${APP_PID}
    fi
    ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e ${APP_PID} ]; then
      echo ${APP_NAME} is running, pid=`cat ${APP_PID}`
   else
      echo ${APP_NAME} is NOT running
      exit 1
   fi
   ;;*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0